import { NavConfig } from "../../types/data/json/sections-json";

export const propertyManagerNavConfig: NavConfig[] = [
  {
    name: "Board",
    hide: true,
    contents: [
      {
        sectionKey: "home",
        title: "",
        subtitle: "",
        title: "TOP",
        link: "/dashboard/home",
        importButton: "",
        createButton: "",
        icon: "Dashboard",
        hide: true,
      },
      {
        sectionKey: "threads",
        title: "Posts",
        subtitle: "subtitle",
        title: "posts",
        link: "/dashboard",
        importButton: "",
        createButton: "",
        icon: "posts",
        hide: true,
      },
      {
        sectionKey: "maintenances",
        title: "maintenances",
        subtitle: "subtitle",
        title: "maintenances",
        link: "/dashboard/maintenances",
        importButton: "",
        createButton: "Assign Maintenance",
        hide: true,
        icon: "posts",
      },
    ],
  },
  {
    name: "main",
    hide: true,
    contents: [
      {
        sectionKey: "statistics",
        title: "Statistics",
        subtitle: "subtitle",
        title: "Statistics",
        link: "/dashboard/statistics",
        importButton: "",
        createButton: "",
        hide: true,
        icon: "Statistic",
      },

      {
        sectionKey: "bookmarks",
        title: "Bookmarks",
        subtitle: "subtitle",
        title: "Bookmark",
        link: "/dashboard/bookmarks",
        importButton: "",
        createButton: "New Bookmark",
        hide: true,
        icon: "Dashboard",
      },
      {
        sectionKey: "comments",
        title: "Comments",
        subtitle: "subtitle",
        title: "Comment",
        link: "/dashboard/comments",
        importButton: "",
        createButton: "New Comment",
        icon: "Dashboard",
        hide: true,
      },
    ],
  },
  {
    name: "setups",
    hide: false,
    contents: [
      {
        sectionKey: "maintainers",
        title: "Maintainers",
        subtitle: "subtitle",
        title: "maintainer",
        link: "/dashboard/maintainers",
        importButton: "",
        createButton: "New maintainer",
        icon: "Dashboard",
        hide: false,
      },
    ],
  },
  {
    name: "admin",
    hide: false,
    contents: [
      {
        sectionKey: "tags",
        title: "Tags",
        subtitle: "subtitle",
        title: "Tag",
        link: "/dashboard/tags",
        importButton: "",
        createButton: "New Tag",
        hide: true,
        icon: "Dashboard",
      },
      {
        sectionKey: "threads",
        title: "Threads",
        subtitle: "subtitle",
        title: "Thread",
        link: "/dashboard/threads",
        importButton: "",
        createButton: "New Thread",
        hide: true,
        icon: "Dashboard",
      },
      {
        sectionKey: "spaces",
        title: "spaces",
        subtitle: "subtitle",
        title: "spaces",
        link: "/dashboard/spaces",
        importButton: "",
        createButton: "New Space",
        icon: "Dashboard",
        hide: false,
      },
      {
        sectionKey: "users",
        title: "Users",
        subtitle: "subtitle",
        title: "User",
        link: "/dashboard/users",
        importButton: "import Excel",
        createButton: "New User",
        icon: "Dashboard",
        hide: false,
      },
    ],
  },
];
