import { ROOT } from '../../path/path-frontend';
import { NavConfig } from '../../types/data/json/sections-json';
import { POSTS, TABLE } from './nav-path';

export const super_admin_nav_configs: NavConfig[] = [
  {
    name: 'Board',
    hide: false,
    contents: [
      {
        title: 'Settings',
        link: '/dashboard/settings',
        icon: 'settings',
        hide: false,
      },
      {
        title: 'Threads',
        link: POSTS('threads'),
        icon: 'posts',
        hide: false,
      },
      {
        title: 'maintenances',
        link: TABLE('maintenances'),
        hide: false,
        icon: 'hammer',
      },
    ],
  },
  {
    name: 'admin',
    roles: ['super_admin', 'admin'],
    hide: false,
    contents: [
      {
        entity: 'tags',
        entitySingle: 'tag',
        title: 'Tags',
        subtitle: 'subtitle',
        navbarTitle: 'Tag',
        link: '/dashboard/tags',
        importButton: '',
        createButton: 'New Tag',
        hide: true,
        icon: 'Dashboard',
      },
      {
        entity: 'threads',
        entitySingle: 'thread',
        title: 'Threads',
        subtitle: 'subtitle',
        navbarTitle: 'Thread',
        link: '/dashboard/threads',
        importButton: '',
        createButton: 'New Thread',
        hide: true,
        icon: 'Dashboard',
      },
      {
        entity: 'spaces',
        entitySingle: 'space',
        title: 'spaces',
        subtitle: 'subtitle',
        navbarTitle: 'spaces',
        link: '/dashboard/spaces',
        importButton: '',
        createButton: 'New Space',
        icon: 'Dashboard',
        hide: false,
      },
      {
        entity: 'users',
        entitySingle: 'user',
        title: 'Users',
        subtitle: 'subtitle',
        navbarTitle: 'User',
        link: '/dashboard/users',
        importButton: 'import Excel',
        createButton: 'New User',
        icon: 'Dashboard',
        hide: false,
      },
    ],
  },
  {
    name: 'Sensitive',
    roles: ['super_admin'],
    hide: false,
    contents: [
      {
        entity: 'uploads',
        entitySingle: 'upload',
        title: 'uploads',
        subtitle: 'subtitle',
        navbarTitle: 'uploads',
        link: '/dashboard/uploads',
        importButton: '',
        createButton: 'New Wallet',
        hide: false,
        icon: 'Dashboard',
      },
      {
        entity: 'wallets',
        entitySingle: 'wallet',
        title: 'Wallets',
        subtitle: 'subtitle',
        navbarTitle: 'Wallets',
        link: '/dashboard/wallets',
        importButton: '',
        createButton: 'New Wallet',
        hide: true,
        icon: 'Dashboard',
      },
      {
        entity: 'userSettings',
        entitySingle: 'userSetting',
        title: 'UserSettings',
        subtitle: 'subtitle',
        navbarTitle: 'User setting',
        link: '/dashboard/userSettings',
        importButton: '',
        createButton: '',
        hide: true,
        icon: 'dashboard',
      },
      {
        entity: 'organizations',
        entitySingle: 'organization',
        title: 'organizations',
        subtitle: 'subtitle',
        navbarTitle: 'organizations',
        link: '/dashboard/organizations',
        importButton: '',
        createButton: 'New Owner',
        icon: 'Dashboard',
        hide: false,
      },
    ],
  },
];
