import { ROOT } from "../../path/path-frontend";
import { NavConfig } from "../../types/data/json/sections-json";
import { POSTS, TABLE } from "./nav-path";

export const super_admin_nav_configs: NavConfig[] = [
  {
    name: "Board",
    key: "board",
    hide: false,
    contents: [
      {
        title: "Settings",
        link: "/super-admin/dashboard/dataTable/settings",
        icon: "settings",
        hide: false,
      },
      {
        title: "Threads",
        link: POSTS("threads"),
        icon: "posts",
        hide: false,
      },
      {
        title: "maintenances",
        link: TABLE("maintenances"),
        hide: false,
        icon: "hammer",
      },
    ],
  },
  {
    name: "admin",
    roles: ["super_admin", "admin"],
    hide: false,
    contents: [
      {
        entity: "tags",
        entitySingle: "tag",
        title: "Tags",
        subtitle: "subtitle",
        navbarTitle: "Tag",
        link: "/super-admin/dashboard/dataTable/tags",
        importButton: "",
        createButton: "New Tag",
        hide: true,
        icon: "Dashboard",
      },
      {
        entity: "threads",
        entitySingle: "thread",
        title: "Threads",
        subtitle: "subtitle",
        navbarTitle: "Thread",
        link: "/super-admin/dashboard/dataTable/threads",
        importButton: "",
        createButton: "New Thread",
        hide: true,
        icon: "Dashboard",
      },
      {
        entity: "spaces",
        entitySingle: "space",
        title: "spaces",
        subtitle: "subtitle",
        navbarTitle: "spaces",
        link: "/super-admin/dashboard/dataTable/spaces",
        importButton: "",
        createButton: "New Space",
        icon: "Dashboard",
        hide: false,
      },
      {
        entity: "users",
        entitySingle: "user",
        title: "Users",
        subtitle: "subtitle",
        navbarTitle: "User",
        link: "/super-admin/dashboard/dataTable/users",
        importButton: "import Excel",
        createButton: "New User",
        icon: "Dashboard",
        hide: false,
      },
    ],
  },
  {
    name: "Sensitive",
    roles: ["super_admin"],
    hide: false,
    contents: [
      {
        entity: "uploads",
        entitySingle: "upload",
        title: "uploads",
        subtitle: "subtitle",
        navbarTitle: "uploads",
        link: "/super-admin/dashboard/dataTable/uploads",
        importButton: "",
        createButton: "New Wallet",
        hide: false,
        icon: "Dashboard",
      },
      {
        entity: "wallets",
        entitySingle: "wallet",
        title: "Wallets",
        subtitle: "subtitle",
        navbarTitle: "Wallets",
        link: "/super-admin/dashboard/dataTable/wallets",
        importButton: "",
        createButton: "New Wallet",
        hide: true,
        icon: "Dashboard",
      },
      {
        entity: "userSettings",
        entitySingle: "userSetting",
        title: "UserSettings",
        subtitle: "subtitle",
        navbarTitle: "User setting",
        link: "/super-admin/dashboard/dataTable/userSettings",
        importButton: "",
        createButton: "",
        hide: true,
        icon: "dataTable",
      },
      {
        entity: "organizations",
        entitySingle: "organization",
        title: "organizations",
        subtitle: "subtitle",
        navbarTitle: "organizations",
        link: "/super-admin/dashboard/dataTable/organizations",
        importButton: "",
        createButton: "New Owner",
        icon: "Dashboard",
        hide: false,
      },
    ],
  },
];
