import { MaintainerSelect } from '../../../src/components/input/custom-inputs/MaintainerSelect';
import {
  MAINTAINER_TYPES,
  MAINTAINER_TYPES_ARRAY,
  MAINTAINER_TYPES_OPTIONS,
  MAINTENANCE_STATUS_ARRAY,
  MAINTENANCE_STATUS_OPTIONS,
} from '../../../src/lib/enums';
import { FormFieldTypes } from '../../../src/types/general/data/data-table/form-field-type/formField-types';

export const maintenancesTableData: Array<FormFieldTypes> = [
  {
    id: 'status',
    name: 'status',
    label: 'Status',
    type: 'static-select',
    options: [...MAINTENANCE_STATUS_OPTIONS],
    // _entity: 'maintenances',
    // selectValues: ['name'],
    required: false,
    textSearch: true,
    priority: 0,
    formOrder: 5,
  },
  {
    id: 'title',
    name: 'title',
    label: 'Title of the maintenance',
    type: 'text',
    textSearch: true,
    required: true,
    priority: 0,
    formOrder: 1,
  },
  {
    id: 'description',
    name: 'description',
    label: 'Description of the maintenance',
    type: 'text-area',
    textSearch: true,
    cellType: 'text-on-dialog',
    minRows: 5,
    required: false,
    priority: 0,
    formOrder: 2,
  },
  {
    id: 'createdAt',
    name: 'createdAt',
    label: 'date of creation',
    type: 'date',
    required: false,
    priority: 0,
    formOrder: false,
  },
  {
    id: 'type',
    name: 'type',
    label: 'Type of maintenance',
    type: 'static-select',
    options: [...MAINTAINER_TYPES_OPTIONS],
    // _entity: 'maintenances',
    // selectValues: ['name'],
    required: false,
    textSearch: true,
    priority: 0,
    formOrder: 3,
  },

  {
    id: 'maintainer',
    name: 'maintainer',
    label: 'Maintainer',
    type: 'custom',
    // textSearch: true,
    required: true,
    component: MaintainerSelect,
    priority: 0,
    formOrder: 4,
  },
  {
    id: 'images',
    name: 'images',
    label: 'Photos',
    type: 'image',
    multi: true,
    // type: 'dropzone',
    accept: 'image/*',
    // selectValues: ['name'],
    required: false,
    priority: 2,
  },
];
